### ISSUE TITLE
Awesome work! Do you have any plan to release the dataset or code?

### ISSUE THREAD

**Issue by Mike001-wq** [qimaqi/ShapeSplat-Gaussian_MAE#1]

**Comment by unique1i** [comment]
Hi, thanks for your interest! We're discussing how to release the dataset in the best manner, it will come sooner. We plan to release the code later.

**Comment by jingwu2121** [comment]
Hi! Amazing work! is there a general dataset release timeline? thanks! :)

**Comment by qimaqi** [comment]
For the data, we expect to release it in September and will also share the code for data generation. As for the experimental code, we plan to release it after the paper is accepted.

**Comment by kevinhuangxf** [comment]
Hi. Looking forward to the dataset release. Thank for your contribution on this fancy work!

**Comment by unique1i** [comment]
We just released the first part of our dataset under the official ShapeNet repo. :D
