### ISSUE TITLE
question about the parallel training

### ISSUE THREAD

**Issue by Roywangj** [qimaqi/ShapeSplat-Gaussian_MAE#3]
hi, thanks for your nice work!  

However, i have a question about the training detail (training gs process). Vanallia MAE technique is implemented on samples of a mini-batch(e.g., bs=64), while the vanillia is implemented on one sample ( bs=1), and the cuda code of 3dgs don't support parallel training. How do you overcome the question, or only looping  the samples of the  minibatch?

**Comment by qimaqi** [comment]
Hi
Thank you for reaching out. If you're inquiring about the Gaussian generation process, please note that it isn't done in parallel. Instead, we submit multiple jobs to different GPUs, with each GPU training on one object at a time.

Best
Qi
