### ISSUE TITLE
How do we use transforms.json to calculate the parameters needed for rendering rasterization?

### ISSUE THREAD

**Issue by Mike001-wq** [qimaqi/ShapeSplat-Gaussian_MAE#5]
Such as world_view_transform, full_proj_transform, camera_center, znear and zfar, etc

**Comment by Mike001-wq** [comment]
I would be very grateful if you could provide the code

**Comment by Mike001-wq** [comment]
I found that the transforms_matrix recorded in transforms.json seems not relative to the 3D Gaussians ply file?

**Comment by unique1i** [comment]
Hi! We record the camera-to-world transformation in the transforms_train.json file, the 72 rendered views are used to train 3DGS, please refer to the original 3DGS repo for data loading.
