### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by JeffreyLuW** [qimaqi/ShapeSplat-Gaussian_MAE#6]
The work is truly impressive! I was wondering if there is an estimated timeline for the code release ?

**Comment by unique1i** [comment]
Thanks for your interest! We currently plan to release the code in November.

**Comment by SravanChittupalli** [comment]
Thank you for the incredible work you’ve shared—it’s truly impressive!

I wanted to check if there are any plans to release the code soon. 

Looking forward to hearing from you!

**Comment by qimaqi** [comment]
Thanks for asking, we are working on some last check, the code will be released potentially this week :)
