### ISSUE TITLE
Train images or COLMAP input

### ISSUE THREAD

**Issue by maincold2** [qimaqi/ShapeSplat-Gaussian_MAE#7]
Thanks for your nice work.

I looked at the ShapeSplat dataset, and it might not contain train images or COLMAP results for 3DGS training.
If so, would you happen to have a plan to release them?

Thanks again!

**Comment by qimaqi** [comment]
Currently, we've only released the trained Gaussian splats dataset. We can also provide the training images, point cloud, and poses in Blender format, but we need to discuss this with the ShapeNet team first.

**Comment by maincold2** [comment]
I see, I'm looking forward to the further release.
Thanks for your response.
